version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
    # volumes:
    # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  avote1:
    command: ["1"]
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./src/tallier
      dockerfile: Dockerfile
    volumes:
      - ./src/tallier:/app/:ro
    secrets:
      - avote_ca.crt
      - source: avote1_key.pem
        target: certfile.pem
    ports:
      # - "18080:8080"
      - "8080:8080"

  avote2:
    command: ["2"]
    depends_on:
      - db
    build:
      context: ./src/tallier
      dockerfile: Dockerfile
    volumes:
      - ./src/tallier:/app/:ro
    secrets:
      - avote_ca.crt
      - source: avote2_key.pem
        target: certfile.pem

  avote3:
    command: ["3"]
    depends_on:
      - db
    build:
      context: ./src/tallier
      dockerfile: Dockerfile
    volumes:
      - ./src/tallier:/app/:ro
    secrets:
      - avote_ca.crt
      - source: avote3_key.pem
        target: certfile.pem

  webserver:
    build: src/webserver
    ports:
      - 80:5000

secrets:
  avote_ca.crt:
    file: ./keys/avote_ca.crt
  avote1_key.pem:
    file: ./keys/avote1.pem
  avote2_key.pem:
    file: ./keys/avote2.pem
  avote3_key.pem:
    file: ./keys/avote3.pem
